config/routes.rb
Rails.application.routes.draw do
  root 'inicio#index'

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  resources :sessions, only: [:create]
  match '/signup', to: 'users#new', via: 'get'
  get 'my_car' => 'users#my_car'
  post 'my_car' => 'users#comprar', as: "comprar"

  get 'buscar_producto' => "inicio#buscar_producto", as: "buscar_producto"
  post "agregar_al_carrito" => "users#agregar_al_carrito"
  post "actualizar_carrito" => "users#actualizar_carrito"
  post 'quitar_linea' => "users#quitar_linea", as: "quitar_linea"

  resources :lines
  resources :products
  resources :categories
  resources :users #, except: [:new]

end

app/models/line.rb
class Line < ActiveRecord::Base
  belongs_to :product
  belongs_to :car
end

app/controllers/lines_controller.rb
class LinesController < ApplicationController
  before_action :set_line, only: [:show, :edit, :update, :destroy]

  # GET /lines
  # GET /lines.json
  def index
    @lines = Line.all
  end

  # GET /lines/1
  # GET /lines/1.json
  def show
  end

  # GET /lines/new
  def new
    @line = Line.new
  end

  # GET /lines/1/edit
  def edit
  end

  # POST /lines
  # POST /lines.json
  def create
    @line = Line.new(line_params)

    respond_to do |format|
      if @line.save
        format.html { redirect_to @line, notice: 'Line was successfully created.' }
        format.json { render :show, status: :created, location: @line }
      else
        format.html { render :new }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lines/1
  # PATCH/PUT /lines/1.json
  def update
    respond_to do |format|
      if @line.update(line_params)
        format.html { redirect_to @line, notice: 'Line was successfully updated.' }
        format.json { render :show, status: :ok, location: @line }
      else
        format.html { render :edit }
        format.json { render json: @line.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lines/1
  # DELETE /lines/1.json
  def destroy
    @line.destroy
    respond_to do |format|
      format.html { redirect_to lines_url, notice: 'Line was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line
      @line = Line.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_params
      params.require(:line).permit(:product_id, :car_id, :cantidad)
    end
end

app/helpers/lines_helper.rb
module LinesHelper
end

app/views/lines/_form.html.erb
<%= form_for(@line) do |f| %>
  <% if @line.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line.errors.count, "error") %> prohibited this line from being saved:</h2>

      <ul>
      <% @line.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :car_id %><br>
    <%= f.text_field :car_id %>
  </div>
  <div class="field">
    <%= f.label :cantidad %><br>
    <%= f.number_field :cantidad %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lines/_line.html.erb
<tr>
  <td>
    <%= image_tag(line.product.imagen, alt: line.product.descripcion, size: "72") %>
  </td>
  <td><%= line.product.descripcion %></td>
  <td><%= line.cantidad %></td>
  <td><%= line.product.precio %></td>
  <td>
    <%= form_tag(actualizar_carrito_url, method: :post) do %>
        <%= text_field_tag :line_id, line.id, type:"hidden" %>
        <%= text_field_tag :cantidad, 0, class:"form-control" %>
        <%= button_tag type:"input", class:"btn btn-danger btn-mini" do %>
            Actualizar
        <% end %>
    <% end %>
  </td>
</tr>

app/views/lines/edit.html.erb
<h1>Editing Line</h1>

<%= render 'form' %>

<%= link_to 'Show', @line %> |
<%= link_to 'Back', lines_path %>

app/views/lines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Lines</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Car</th>
      <th>Cantidad</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lines.each do |line| %>
      <tr>
        <td><%= line.product %></td>
        <td><%= line.car %></td>
        <td><%= line.cantidad %></td>
        <td><%= link_to 'Show', line %></td>
        <td><%= link_to 'Edit', edit_line_path(line) %></td>
        <td><%= link_to 'Destroy', line, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Line', new_line_path %>

app/views/lines/new.html.erb
<h1>New Line</h1>

<%= render 'form' %>

<%= link_to 'Back', lines_path %>

app/views/lines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @line.product %>
</p>

<p>
  <strong>Car:</strong>
  <%= @line.car %>
</p>

<p>
  <strong>Cantidad:</strong>
  <%= @line.cantidad %>
</p>

<%= link_to 'Edit', edit_line_path(@line) %> |
<%= link_to 'Back', lines_path %>