config/routes.rb
Rails.application.routes.draw do
  root 'inicio#index'

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  resources :sessions, only: [:create]
  match '/signup', to: 'users#new', via: 'get'
  get 'my_car' => 'users#my_car'
  post 'my_car' => 'users#comprar', as: "comprar"

  get 'buscar_producto' => "inicio#buscar_producto", as: "buscar_producto"
  post "agregar_al_carrito" => "users#agregar_al_carrito"
  post "actualizar_carrito" => "users#actualizar_carrito"
  post 'quitar_linea' => "users#quitar_linea", as: "quitar_linea"

  resources :lines
  resources :products
  resources :categories
  resources :users #, except: [:new]

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :products, join_table: "categorization"
	validates :titulo, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user
  before_action :user_is_admin

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.paginate(page:params[:page], per_page:25)
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @products = @category.products.paginate(page: params[:page], per_page: 4)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:titulo, :descripcion)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div class="col-xs-6 col-lg-4 image">
  <%= link_to category_path(category) do %>
    <h2><%= category.titulo %></h2>
  <% end %>
</div>

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :titulo %><br>
    <%= f.text_field :titulo, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :descripcion %><br>
    <%= f.text_area :descripcion, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editando Category</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @category %> |
<%= link_to 'Atrás', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listando Categorias</h1>
<%= will_paginate @categories %>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Título</th>
    <th>Descripción</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @categories.each do |category| %>
      <tr>
        <td><%= category.titulo %></td>
        <td><%= category.descripcion %></td>
        <td>
          <%= link_to 'Mostrar', category %>
          <%= link_to 'Editar', edit_category_path(category) %>
          <%= link_to 'Destruir', category, method: :delete, data: { confirm: '¿Estas seguro?' } %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>
<%= will_paginate @categories %>
<br>

<%= link_to 'New Categoría', new_category_path %>

app/views/categories/new.html.erb
<h1>Nuevo Categoría</h1>

<%= render 'form' %>

<%= link_to 'Atrás', categories_path %>

app/views/categories/show.html.erb
<% provide(:title, 'Categoria '+@category.id.to_s) %>
<div class="row">
  <p id="notice"><%= notice %></p>
  <h1 class="page-header">
    <%= @category.titulo %>
  </h1>
  <p class="lead">
    <%= @category.descripcion %>
  </p>
</div>
<% if @products.any? %>
    <div class="row">
      <%= will_paginate @products %>
    </div>
    <div class="row">
      <%= render @products %>
    </div>
    <div class="row">
      <%= will_paginate @products %>
    </div>
<% end %>
<%= link_to "Editar", edit_category_url(@category) %> |
<%= link_to "Atrás", categories_url %>