config/routes.rb
Rails.application.routes.draw do
  root 'inicio#index'

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  resources :sessions, only: [:create]
  match '/signup', to: 'users#new', via: 'get'
  get 'my_car' => 'users#my_car'
  post 'my_car' => 'users#comprar', as: "comprar"

  get 'buscar_producto' => "inicio#buscar_producto", as: "buscar_producto"
  post "agregar_al_carrito" => "users#agregar_al_carrito"
  post "actualizar_carrito" => "users#actualizar_carrito"
  post 'quitar_linea' => "users#quitar_linea", as: "quitar_linea"

  resources :lines
  resources :products
  resources :categories
  resources :users #, except: [:new]

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_and_belongs_to_many :categories, join_table: "categorization"
  # accepts_nested_attributes_for :categories
  has_many :lines, dependent: :destroy
  validates :precio, numericality: { greather_than_or_equal_to: 0 }
  validates :titulo, uniqueness: true
  validates :titulo, :descripcion, :imagen, :precio, :categories, presence: true
  validates_format_of :imagen, :with => %r{\.(png|jpg|jpeg)}i
  after_initialize {
	 	 self.imagen = "product.png" if self.imagen.blank?
	}
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :signed_in_user
  before_action :user_is_admin

  # GET /products
  # GET /products.json
  def index
    @products = Product.paginate(page: params[:page], per_page:25)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:titulo, :descripcion, :imagen, :precio, category_ids: [])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibieron que este producto se comience ha guardar:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :titulo %>
    <%= f.text_field :titulo, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :descripcion %>
    <%= f.text_area :descripcion, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :imagen %>
    <%= f.text_field :imagen, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :precio %>
    <%= f.text_field :precio, class:"form-control" %>
  </div>
    <div class="form-group">
      <%= f.label :categories %>
      <%= f.select :category_ids, Category.all.collect {|c| [c.titulo, c.id] }, {},
                   {multiple: true, class:"form-control"} %>
    </div>
  <div class="form-group">
    <%= f.submit "Actualizar Producto", class:"btn btn-success" %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="col-xs-6 col-lg-4">
  <%= image_tag(product.imagen, alt: product.titulo, class: "img-responsive") %>
  <h2><%= product.titulo %></h2>
  <%= link_to "Descripción", product_path(product) %>
  $<span><%= product.precio %></span>
  <div class="row">
    <div class="col-lg-8">
      <%= form_tag(agregar_al_carrito_url, remote: true) do %>
          <div class="input-group">
            <%= text_field_tag "cantidad", 1, class:"form-control", placeholder:"Cantidad", required: true %>
            <%= text_field_tag "product_id", product.id, type: "hidden" %>
            <span class="input-group-btn">
              <%= button_tag "Al carrito!", class: "btn btn-primary" %>
            </span>
          </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Editando Producto</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @product %> |
<%= link_to 'Atrás', products_path %>

app/views/products/index.html.erb
<% provide(:title, 'Lista de Productos') %>
<h1>Lista de Productos</h1>
<%= will_paginate @products %>
<div class="row">
  <table class="table table-striped">
    <thead>
    <tr>
      <th>Título</th>
      <th>Descripción</th>
      <th>Imagen</th>
      <th>Precio</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @products.each do |product| %>
        <tr>
          <td><%= product.titulo %></td>
          <td><%= product.descripcion %></td>
          <td><%= product.imagen %></td>
          <td><%= product.precio %></td>
          <td>
            <%= link_to 'Mostrar', product %>
            <%= link_to 'Editar', edit_product_path(product) %>
            <%= link_to 'Destruir', product, method: :delete, data: { confirm: '¿Estas seguro?' } %>
          </td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>
<%= will_paginate @products %>
<br>

<%= link_to 'Nuevo Producto', new_product_path %>

app/views/products/new.html.erb
<h1>Nuevo Producto</h1>

<%= render 'form' %>

<%= link_to 'Atrás', products_path %>

app/views/products/show.html.erb
<% provide(:title, 'Producto '+@product.id.to_s) %>
<div class="row">
  <h2 class="page-header">
    <%= @product.titulo %>
  </h2>
  <%= form_tag(agregar_al_carrito_url, remote: true, class: "form-inline") do %>
      <div class="input-group">
        <%= text_field_tag "cantidad", 1, class:"form-control", placeholder:"Cantidad", required: true %>
        <%= text_field_tag "product_id", @product.id, type: "hidden" %>
        <span class="input-group-btn">
              <%= button_tag "Al carrito!", class: "btn btn-primary" %>
            </span>
      </div>
  <% end %>
  <p><strong> $<%= @product.precio %></strong></p>
  <p class="lead">
    <%= @product.descripcion %>
  </p>
</div>
<div class="row">
  <%= image_tag(image_url(@product.imagen), alt: "producto") %>
</div>
<%= link_to "Editar", edit_product_url(@product) %> |
<%= link_to "Atrás", products_url %>