config/routes.rb
Rails.application.routes.draw do
  root 'inicio#index'

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: 'delete'
  resources :sessions, only: [:create]
  match '/signup', to: 'users#new', via: 'get'
  get 'my_car' => 'users#my_car'
  post 'my_car' => 'users#comprar', as: "comprar"

  get 'buscar_producto' => "inicio#buscar_producto", as: "buscar_producto"
  post "agregar_al_carrito" => "users#agregar_al_carrito"
  post "actualizar_carrito" => "users#actualizar_carrito"
  post 'quitar_linea' => "users#quitar_linea", as: "quitar_linea"

  resources :lines
  resources :products
  resources :categories
  resources :users #, except: [:new]

end

app/views/layouts/_footer.html.erb
<footer>
  <p class="pull-right"><a href="#">Back to top</a></p>
  <p>© 2016 Company, Inc. · <a href="#">Privacy</a> · <a href="#">Terms</a></p>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Tienda Virtual", root_path, class: "navbar-brand" %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="navbar-form navbar-right">
        <% if signed_in? %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                 aria-haspopup="true" aria-expanded="false"><%= current_user.login %> <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><%= link_to "<i class=\"icon-user\"></i> Perfil".html_safe, current_user %></li>
                <li><%= link_to "<i class=\"icon-cog\"></i> Configuración".html_safe, edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "<i class=\"icon-off\"></i> Cerrar sesión".html_safe, signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
        <% else %>
            <%= link_to "Registrarte", signup_path, {class: "btn btn-primary"} %>
            <%= link_to "Iniciar Sesión", signin_path, {class: "btn btn-success"} %>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>La Tienda Virtual | <%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<div class="container">
  <div class="row row-offcanvas row-offcanvas-right">
    <div class="col-xs-12 col-sm-9">
      <p class="pull-right visible-xs">
        <button type="button" class="btn btn-primary btn-xs" data-toggle="offcanvas">Menú Usuario</button>
      </p>
      <%= yield %>
    </div>
    <div class="col-xs-6 col-sm-3 sidebar-offcanvas" id="sidebar">
      <% if signed_in? %>
          <%= image_tag("imagen_predefinida.png", alt: "usuario") %>
          <%= link_to "Mi carrito", my_car_path %>
      <% end %>
      <hr>
      <%= form_tag(buscar_producto_path, method: :get) do %>
          <div class="form-group">
            <%= text_field_tag "titulo", nil, placeholder: "buscar producto", class: "form-control" %>
          </div>
      <% end %>
    </div>
  </div>
  <%= render 'layouts/footer' %>
</div>
</body>
</html>